[build]
  base = "/"
  publish = "public"
  functions = "functions"
  command = "npm start"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  functionsPort = 34567

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
