[build]
  base = "/"
  publish = "public"
  functions = "functions"
  command = "npm start"

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Adjust based on your project setup

[dev]
  functionsPort = 34567

[[redirects]]
  from = "/*"
  to = "/views/index.ejs"
  status = 200
  force = true
